### ISSUE TITLE
需要一些帮助：从Steam钱包到Buff 

### ISSUE THREAD

**Issue by NumseBacon** [EricZhu-42/SteamTradingSiteTracker#30]
嘿伙计们，

我正在尝试从我的Steam钱包搞点钱进Buff，但实际上这场游戏比我想象的要棘手。就我看来，Buff上的大多数皮肤比Steam低大约20%，导致每次交易都会有一些损失。

我知道这是常见的，但这里一定有别的方法吧？如果有人能提供关于找到更好交易皮肤的建议或者搞定这个20%价格下降的窍门，那将非常酷

**Comment by EricZhu-42** [comment]
Hi there,

Our website (iflow.work) is specifically designed to search for the best items to buy on BUFF and sell on the Steam Market, so it won't be of much help in your case. We've implemented tailored filters to exclude "undesirable" items from our database, meaning you're unlikely to find really good deals based on our data.

If you have a substantial number of items to sell, I would suggest using our code to set up your own price-tracking service. You can reverse the filtering rules so that only the most favorable items for you are saved and regularly updated.

If that's not the case, you can try searching for keywords like "STEAM 余额套现" or "STEAM 高比例饰品" to find relevant information. Baidu usually provides better results than Google for these specific keywords. If you'd like some articles on recently updated deal suggestions, feel free to [send me an email](mailto:zhuxinhao00@gmail.com).

---

与 #27 , #21 类似，暂不计划开发钱包余额转卖相关的功能；有需求的朋友可以在部署本站代码时修改饰品的筛选规则，例如：
https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/7e3c8e53107762db0fc0fc2311e357ed30c1b187/scripts/update_meta.py#L165-L166
调整为仅保留比例较高的饰品，应该有助于获得最适合余额转卖的饰品价格信息。

**Comment by NumseBacon** [comment]
嘿。

谢谢你的快速回复! 我一直在使用iflow.work，它对从Buff到Steam的引导非常好，同时也在尝试是否可以反向使用它。这个工具很方便，但由于价格差异，要从Steam为Buff找到好的交易，有点挑战性。

你关于建立我自己的价格跟踪服务的想法听起来很有希望，这绝对是我要考虑尝试的事情。如果我能够想出办法的话，哈哈

至于在百度上使用 "STEAM套现 "和 "STEAM高比例物品 "这样的关键词，这是一个很好的建议，但我的中文不是很好，所以可能会有一些困难。
